language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
before_install:
  - git fetch --tags
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
node_js: '8.10'

stages:
  - name: test
    # require the event type to not be a semantic release tag.
    if: NOT tag =~ ^v\d+\.\d+\.\d+$
  - name: deploy-dev
    if: branch = dev AND fork = false AND type IN (push, api)
  - name: release
    if: branch = dev AND fork = false AND type IN (push, api)
  - name: deploy-prod
    if: branch = prod AND fork = false AND type IN (push, api)

jobs:
  include:
    - stage: test
      script:
        - yarn lint
        - yarn test

    - stage: deploy-dev
      script:
        - yarn sls deploy -s dev -v && yarn sls -s dev files

    - stage: release
      script: yarn semantic-release

    - stage: deploy-prod
      script:
        - yarn sls deploy -s production -v && yarn sls -s production files
