language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
before_install:
  - git fetch --tags
script:
  - yarn lint
  - yarn test
branches:
  except:
    - /^v\d+\.\d+\.\d+$/

stages:
  - name: test
    # require the event type to not be a semantic release tag.
    if: NOT tag =~ ^v\d+\.\d+\.\d+$
  - name: deploy-dev
    # require the branch name to be one of the environment branches.
    if: branch = dev AND fork = false AND type IN (push, api)
  - name: deploy-prod
    # require the branch name to be one of the environment branches.
    if: branch = prod AND fork = false AND type IN (push, api)

jobs:
  include:
    - stage: test
      node_js: 'lts/boron'

    - stage: test
      node_js: 'lts/carbon'

    - stage: deploy-dev
      # Semantic release will fail if it's not using node 8.
      node_js: 'lts/carbon'
      script: yarn semantic-release

    - stage: deploy-dev
      node_js: 'lts/boron'
      script:
        - yarn --production
        - yarn sls deploy -s dev -v && yarn sls -s dev files

    - stage: deploy-prod
      node_js: 'lts/boron'
      script:
        - yarn --production
        - yarn sls deploy -s production -v && yarn sls -s production files
